### ISSUE TITLE
Debounce trigger button

### ISSUE THREAD

**Issue by ShockedOne** [ShockedOne/ii-kis-lab#6]
The button responsible for triggering the servo action has a bouncing signal level. This behaviour causes the algorithm to release several balls in a short sequence instead of one ball per button interaction. As we cannot modify the hardware as such there needs to be a software solution to that.

One could for instance think about a timeout.

**Comment by danielS91** [comment]
Maybe a simple timestamp, like:

if ((millis()-last > constraint)
then
  set buttonPressed = true
  set last
else
  set buttonPressed = false

??

**Comment by danielS91** [comment]
??
